import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import { db } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const user = await db.user.findMany
  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  );
}
